### ISSUE TITLE
How to "ivreg" binary or time-to-event outcome?

### ISSUE THREAD

**Issue by jielab** [remlapmot/OneSampleMR#9]
Hi, there:

Thanks for providing **OneSampleMR** package. Previously I have only used **TwoSampleMR** package.

I now have two basic questions:

1. For your first example **fit1 <- ivreg::ivreg(Y ~ X | Z, data = dat1)**,  how to modify this line if **Y is a binary disease trait or a time-to-event object** from the Survival analysis?

2. For TwoSampleMR, we demand/desire that the summary statistics of two datasets (exposure, outcome) were generated from two studies without **overlapping samples**. But for OneSampleMR, it is from one single dataset, therefore exposure and outcome are COMPLETELY overlapping. How do we explain this?

Your feedback is greatly appreciated. 

Thank you & best regards,
Jie

**Comment by remlapmot** [comment]
1. For a binary outcome you can either estimate a causal risk difference, causal risk ratio, or causal odds ratio. This package provides functions for the first two

   <https://remlapmot.github.io/OneSampleMR/reference/asmm.html>

   <https://remlapmot.github.io/OneSampleMR/reference/msmm.html>

   And I do have code for the logistic structural mean model - I just haven't generalised it.

   For time to event outcomes see some of the functions in the [**ivtools**](https://cran.r-project.org/package=ivtools) package.

2. Single sample estimators were defined before two-sample estimators, you can say you are doing a one-sample estimation.

**Comment by jielab** [comment]
Thanks!

It would be great if you could generalise your code for the logistic structural mean model. I am sure that would be useful for a lot of your readers.

Best regards,
Jie
